# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'ProtraitPicker' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SVProgressHUD'
  # Pods for ProtraitPicker

  target 'ProtraitPickerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProtraitPickerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
